### ISSUE TITLE
rsnorm issue

### ISSUE THREAD

**Issue by GawainProdigy** [JarodMica/audiobook_maker#107]
hi Jared,

Thanks a lot for being so close to sharing all this information on tts. i'm running into these issues when i start the program:

F5-TTS is not available, received error: cannot import name 'RMSNorm' from 'x_transformers' (C:\audiobook_maker\audiobook_maker\venv\Lib\site-packages\x_transformers\__init__.py)
[2024-12-05 13:56:21,011] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-12-05 13:56:21,013] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
W1205 13:56:21.430000 14512 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

i'm running windows 10. i already searched the internet and i went through chatgpt. 

in the end the chatGPT asked me to refer to you. thanks for having patience with a noob.

**Comment by JarodMica** [comment]
Ur welcome :)! 

Check your version of torch, RMS norm is only available in 2.4 and above.

> Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.

It may also be due to this. Unfortunately, if you're not running an Nvidia GPU, F5TTS generation is going to be prohibitively large for any practical use cases ATM on CPU

**Comment by JarodMica** [comment]
Please open if you need any more assistance!
