### ISSUE TITLE
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*.

### ISSUE THREAD

**Issue by Evox-id** [JarodMica/audiobook_maker#11]
(venv) PS C:\Users\Evox\Videos\ab\audiobook_maker> pip install -e git+https://github.com/JarodMica/rvc-tts-pipeline.git#egg=rvc_tts_pipe
Obtaining rvc_tts_pipe from git+https://github.com/JarodMica/rvc-tts-pipeline.git#egg=rvc_tts_pipe
  Cloning https://github.com/JarodMica/rvc-tts-pipeline.git to c:\users\evox\videos\ab\audiobook_maker\venv\src\rvc-tts-pipe
  Running command git clone --filter=blob:none --quiet https://github.com/JarodMica/rvc-tts-pipeline.git 'C:\Users\Evox\Videos\ab\audiobook_maker\venv\src\rvc-tts-pipe'
  Resolved https://github.com/JarodMica/rvc-tts-pipeline.git to commit e31ad03d43161a9edbe71fdb07e8ae96fd473de5
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: rvc_tts_pipe
  Building editable for rvc_tts_pipe (pyproject.toml) ... done
  Created wheel for rvc_tts_pipe: filename=rvc_tts_pipe-0.1-0.editable-py3-none-any.whl size=3349 sha256=016803c7181a926e29ebc14cdacd7f20c631f08d2894d13dbe244bfd50e2970b
  Stored in directory: C:\Users\Evox\AppData\Local\Temp\pip-ephem-wheel-cache-c_y8lt0b\wheels\6f\63\f1\dc19d678e054f185392aff9858220e8daff72e4b6008fa47a9
Successfully built rvc_tts_pipe
**DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063**
Installing collected packages: rvc_tts_pipe
Successfully installed rvc_tts_pipe-0.1
(venv) PS C:\Users\Evox\Videos\ab\audiobook_maker>

**Comment by JarodMica** [comment]
This is a fairseq issue that doesn't break the project, it will still run fine with it.
