### ISSUE TITLE
It Keeps Truncating periods and splitting sentences in weird ways

### ISSUE THREAD

**Issue by jackcorns421** [JarodMica/audiobook_maker#15]
Thank you for your hard work.  This is awesome, but it seems to have a problem with the way it splits up the text into separate lines. it also truncates periods and messes up the pronunciation of abbreviations.

For example:

Mr. Smith and Ms. Johnson live in St. Louis by a lake. Mr. Smith works for the C.I.A., and Ms. Johnson works for the D.E.A. as a secretary. One day, on the way home from work, Mr. Smith got a D.U.I. He blew a 0.9, and his B.A.C. was high enough to land him a night in jail.

Gets broken up like this:

1. Mr
2. Smith and Ms
3. Johnson live in St
4. Luis by a lake
5. Mr
6. Smith works for the C.I.A, and Ms
7. Johnson works for the D.E.A
8. as a secretary
9. One day, on the way home from work, Mr
10. Smith got a D.U.I
11. He blew a 0.9, and his B.A.C
12. was high enough to land him a night in jail.

If I paste the above text into Tortoise it all sounds good and works as expected. When using the audio book maker it gets split up and the output is un usable.

**Comment by JarodMica** [comment]
Shoot, that's because of the custom cleaner that I'm using to parse sentences, I'll have to modify it a bit and incorporate that in the next patch.

Thank you for the feedback and for using it!

**Comment by JarodMica** [comment]
This is resolved in the latest commit, I'll be working on some other bug fixes and getting them in for a patch in a package release soonish

**Comment by JarodMica** [comment]
Added to package and updated release.
