### ISSUE TITLE
not a issue just a request

### ISSUE THREAD

**Issue by viktorblack** [JarodMica/audiobook_maker#16]
a highlighter for sentences when need to regenerate sentences but the audio book is still running that i can highlight the sentence's and do it later without having to remember which ones i need to regenerate sry if am not clear English is not my main language 

btw another request would be a way to have a voice select for different speakers that would be amazing

love the tool tho its looking good

**Comment by JarodMica** [comment]
These sound good, I'll add them to the to do list!
