### ISSUE TITLE
software unexpectedly closes when attempting to generate speech.

### ISSUE THREAD

**Issue by Evox-id** [JarodMica/audiobook_maker#19]
After successfully installing Audio Book version 1.0 and exploring various voices, I found that the voice quality was satisfactory but noticed issues with prosody and tone. To address this, I attempted to train a custom voice model using  Tortoise-TTS that gave me 1.59 GB.pth file. i copy pasted file into the Audio Book software. The software unexpectedly closes when attempting to generate speech. I have attached text file that is output of terminal. I seek guidance on resolving this issue.
[text.txt](https://github.com/JarodMica/audiobook_maker/files/12862796/text.txt)

**Comment by Evox-id** [comment]
i managed to searched this huggingface link, it has various voice models.
https://huggingface.co/sanya098111/download-model-rvc/tree/main
I've come to understand that voice models should be trained using RVC rather than Tortoise-TTS.

**Comment by JarodMica** [comment]
Yes, the voice models inside of the audiobook maker are RVC ones specifically, glad you were able to resolve the issue!
