### ISSUE TITLE
omegaconf Do I have to do anything about it?

### ISSUE THREAD

**Issue by rapatapa** [JarodMica/audiobook_maker#2]
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by JarodMica** [comment]
As of right now, no need to worry about that as long as it still works.  It shouldn't cause any issues at this time
