### ISSUE TITLE
Regenerated audio doesn't change. 

### ISSUE THREAD

**Issue by Jaredlands** [JarodMica/audiobook_maker#21]
Since I don't see it posted here, I must be doing something wrong. When I regenerate audio and replay, it doesn't change. I do have the new audio in the results folder but it doesn't replace it in the GUI.

**Comment by JarodMica** [comment]
Is this occurring during any functionality in particular, such as after loading an audiobook, after finishing a generation, etc?  I don't have a way to reproduce this and it's working correctly on my end.

Are you seeing any other errors in the command line window?

**Comment by Jaredlands** [comment]
No errors. It seems to only happen with the fine tuned voices. Auto regressive works flawlessly.
