### ISSUE TITLE
Feature Request: In-App Text Entry for Immediate Testing

### ISSUE THREAD

**Issue by FrnklyN** [JarodMica/audiobook_maker#25]
Hi Jard,
Firstly, I'd like to commend you on the fantastic job you've done with the audiobookmaker. It operates seamlessly! However, I believe it would greatly benefit from an additional feature. Specifically, the ability to input text directly within the app would be immensely useful. This would allow users to quickly type and test individual sentences on-the-fly.

**Comment by viktorblack** [comment]
yes i would love this aswell
