### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Atoli** [JarodMica/audiobook_maker#29]
OS: Windows 10
GPU: Nvidia RTX 3060 12gb

I installed and ran some sentences of mrq's Tortoise Fork to know that it's working correctly.
When i use a txt with audiobook_maker i get the following error:

![error](https://github.com/JarodMica/audiobook_maker/assets/43733214/f893e290-ad48-4227-b350-98b36bc4525d)

Left is audiobook_maker.
Right is mrq's Tortoise.

What exactly i am doing wrong?
I notice audiobook_maker does not try the port opened by Tortoise, no matter how many different ports it opens:

![error2](https://github.com/JarodMica/audiobook_maker/assets/43733214/0236220e-804e-45fd-870f-c052ee027a11)

If it is on port 7860 (like the image) it will start from 7861.
If it is on port 7863 it will start on 7860 then go up but skip 7863.

What could the issue be?

**Comment by pishabh625** [comment]
**I think the below YouTube video will help you with this:**

https://youtu.be/xbheTi1YjnM?si=RlZzWtFcFm9E6Zx3&t=294

**Comment by JarodMica** [comment]
> OS: Windows 10 GPU: Nvidia RTX 3060 12gb
> 
> I installed and ran some sentences of mrq's Tortoise Fork to know that it's working correctly. When i use a txt with audiobook_maker i get the following error:
> 
> ![error](https://private-user-images.githubusercontent.com/43733214/291742770-f893e290-ad48-4227-b350-98b36bc4525d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMyNzIsIm5iZiI6MTcwNTkxMjk3MiwicGF0aCI6Ii80MzczMzIxNC8yOTE3NDI3NzAtZjg5M2UyOTAtYWQ0OC00MjI3LWIzNTAtOThiMzZiYzQ1MjVkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxN2Q4ZTQ5ZGVkMDgzMGRkNzBjZjRjNTk0MmFmMzE5OWM0MzZkYzg0ZGJkNTAxMWNjOWVmMDc0ZTQ0YjkzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.61GMxGnRfk13KsivMLa-ocbAoEPuIRiwT2SNrcsCoFU)
> 
> Left is audiobook_maker. Right is mrq's Tortoise.
> 
> What exactly i am doing wrong? I notice audiobook_maker does not try the port opened by Tortoise, no matter how many different ports it opens:
> 
> ![error2](https://private-user-images.githubusercontent.com/43733214/291743210-0236220e-804e-45fd-870f-c052ee027a11.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMyNzIsIm5iZiI6MTcwNTkxMjk3MiwicGF0aCI6Ii80MzczMzIxNC8yOTE3NDMyMTAtMDIzNjIyMGUtODA0ZS00NWZkLTg3MGYtYzA1MmVlMDI3YTExLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjBiNDIzN2I5Nzk2YjgwYjMyNjdmZmEwZjVhNzkwZTc4NGU1MGJmNmI2ZWJlNDM3YjliYTU5MDQ2YWE1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixpVWYEwAt9Ae_9zwpNeWWxQ0RLj8t7xEpuWczW7F3E)
> 
> If it is on port 7860 (like the image) it will start from 7861. If it is on port 7863 it will start on 7860 then go up but skip 7863.
> 
> What could the issue be?

Hey Atoli, you would need to setup the tort.yaml file as shown in the video, replacing "insert_trained_name" with the one that you are using for tortoise.

Closing the issue, feel free to open it back up if you still need help with this.

**Comment by trialerror-1234** [comment]
Hello, I am having the same problem, even though I followed the steps in the video. I also edited the tort file like in the video. I tried naming it "tort.yaml" but when I do, I get this error:  :( 

![Screenshot (594)](https://github.com/JarodMica/audiobook_maker/assets/168299454/d063643c-0b86-47ba-8fe1-ebd98de429ba)
![Screenshot (595)](https://github.com/JarodMica/audiobook_maker/assets/168299454/d490e259-f3c1-434a-8b18-5b2ffb7108e4)
![tort yaml error](https://github.com/JarodMica/audiobook_maker/assets/168299454/b9341562-5332-4c82-b65d-d5c2e0ba815a)
