### ISSUE TITLE
Webgui and CLI version? maybe?

### ISSUE THREAD

**Issue by rony432** [JarodMica/audiobook_maker#3]
hey jarod

very nice put together video and code

are there going to be a Webgui and CLI version of this repo?

it would be nice. thanks anyway

**Comment by JarodMica** [comment]
Maybe a Webgui but not a CLI as it cannot achieve the functionality of the GUI without it having to be very verbose.  Appreciate the thanks!

**Comment by rony432** [comment]
dont forget the API in webgui :)
