### ISSUE TITLE
Exported Audiobook files are 0 second length empty wav files.

### ISSUE THREAD

**Issue by Artholos** [JarodMica/audiobook_maker#4]
When I export an audiobook, it names the file "Audio Files_audiobook_0" regardless of what the name is set to in the application. The audio file that is supposed to be the stitched together audio parts is simply an empty .wav file with no content.

This behavior is reproducible on my system.

Platform: Windows 10
CPU: Processor AMD Ryzen 7 5800X
GPU: RTX 3090 Ti
RAM: 64GB

**Comment by JarodMica** [comment]
Could you layout the steps for reproducibilty? Is it when doing it on a finished audiobook?

**Comment by Artholos** [comment]
After writing my combine program and then reading through the code, I now realize I was doing it wrong.

The export is not for choosing where to export the file, but where to find the audio files to combine.

I think that's a bit confusing because typically 'exporting' a project in other programs like Gimp, Premiere, Audacity, etc have you choose where the file will be located once it's done combining the elements in the current project.
