### ISSUE TITLE
Failed to connect to port 7860, trying next port TypeError: cannot unpack non-iterable NoneType object 

### ISSUE THREAD

**Issue by trialerror-1234** [JarodMica/audiobook_maker#43]
Hello, I keep having the same problem, even though I followed the steps in the video tutorial. I also edited the tort file like in the video. I tried naming it "tort.yaml" but when I do, I get this error:

**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Downloads\\audiobook_maker_v1.1\\tort.yaml**

![tort yaml error](https://github.com/JarodMica/audiobook_maker/assets/168299454/c11ac74e-9bd3-41fc-97ac-703bbc2061ec)

And when I remove the .yaml part, and save it as only "tort", I keep getting the same results 

![Screenshot (594)](https://github.com/JarodMica/audiobook_maker/assets/168299454/f7f01279-d10b-4e19-b522-aa87470904bc)
![Screenshot (595)](https://github.com/JarodMica/audiobook_maker/assets/168299454/c6e083bf-fc04-4204-b4e2-5fb8bf2e042b)

**Comment by Meerfelix** [comment]
this was connected to ther audio cloner version to me. it worked with ai voice cloning 2.0 not 3.0 for me. must be up and runnig first oc.

**Comment by Meerfelix** [comment]
@JarodMica I think it may be worth to confirm that compatibility issue and then flag this in the requirements/descriptions.

**Comment by trialerror-1234** [comment]
> this was connected to ther audio cloner version to me. it worked with ai voice cloning 2.0 not 3.0 for me. must be up and runnig first oc.

I'll try downloading the 2.0 version and see if that works out for me. thank you.
