### ISSUE TITLE
Line Breaks in text/audio Audiobook-Maker GUI display do not always conform to line breaks from source .txt file

### ISSUE THREAD

**Issue by Artholos** [JarodMica/audiobook_maker#5]
There are two behaviors in this issue:

1. The program often omits line breaks from source .txt file, which causes multiple sentences to be rendered in one line. This has the consequence of causing unwanted regeneration for some sentences and increased time to regenerate the line.

2. The program injects line breaks that were not present in the source file, typically after punctuation marks.

Here are some example scenarios I've encountered that have caused trouble for me:

In order for Tortoise to read acronyms correctly, Tortoise needs them to be written "A.B.C." to read out the phonetic title of the characters. If an acronym is written "ABC", there's a high probability Tortoise will read it like 'ahbkha' instead of 'ay-bee-see'. Unfortunately Audiobook Maker often interprets the final period and space characters in the acronym a line break and separates the sentence into two audio renders. This has the consequence of creating sentences that have the wrong inflection and intonations when listening to the audio file un-interrupted.

In addition, very long sentences with many appositives are best to generate in multiple lines so that if one appositive portion of the sentence had a poor render, the entire sentence does not need to be regenerated. Audiobook Maker however does not recognize line breaks after commas, and will concatenate lines together if the line above was ultimately punctuated with a comma.

**Comment by JarodMica** [comment]
Would you be able to post some example sentences for the desired result to be sent over to tortoise? 

Currently there's a function that handles the passing and I would need to adjust some things there. It converts new lines to spaces and then makes sure that the minimum length of a "chunk" sent to tortoise is at least 130 characters meaning 2 sentences could be sent if they're too short.

May be able to add some additional "advanced" settings to change the behavior of the functions or adjust it entirely

**Comment by Artholos** [comment]
![image](https://github.com/JarodMica/audiobook_maker/assets/135184826/cede3be8-3342-40eb-85fb-7d69ffd7e5ad)
![image](https://github.com/JarodMica/audiobook_maker/assets/135184826/255f8455-cc0e-43a3-9a25-c7fdd5a05770)

**Comment by Artholos** [comment]
This text file had the sentences concatenated into 2 audio renderings.

**Comment by Artholos** [comment]
Oops I accidentally closed the issue. hehe sorry

**Comment by JarodMica** [comment]
Resolved here: https://github.com/JarodMica/audiobook_maker/commit/9080f9bf967c77a355fdff184c81f22c1af12314

Let me know if you run into anything else :)!
