### ISSUE TITLE
Manual Installation - Terminal output

### ISSUE THREAD

**Issue by OtterNas3** [JarodMica/audiobook_maker#60]
Hey Jarod!

Congrats on the release of Your Project!
I actually dont wanna know how many time you spent on this, it must have been time consuming

After doing a manual install, this is what i get in the Terminal Window

`[2024-10-21 16:07:27,684] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: Eingabedatei "aio.lib" kann nicht geöffnet werden.
test.c
LINK : fatal error LNK1181: Eingabedatei "cufile.lib" kann nicht geöffnet werden.
W1021 16:07:35.216000 21432 torch\distributed\elastic\multiprocessing\redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.`

Something to worry about, or you need to look at?

Moo,
Otter

**Comment by edbartz** [comment]
I am seeing the same error:
[2024-10-21 12:06:43,454] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
RVC not installed, received error: CUDA_HOME does not exist, unable to compile CUDA op(s)
