### ISSUE TITLE
fatal error LNK1181: cannot open input file 'cufile.lib' / 'aio.lib'

### ISSUE THREAD

**Issue by OnurTumer91** [JarodMica/audiobook_maker#61]
` [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
test.c
LINK : fatal error LNK1181: cannot open input file 'cufile.lib'
W1022 00:32:47.211000 56668 torch\distributed\elastic\multiprocessing\redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.`

Is it some conflict with the cuda/torch?

**Comment by JarodMica** [comment]
This is ok. It's a message from deepspeed and does not cause any issues
