### ISSUE TITLE
Tortoise and RVC don't work.

### ISSUE THREAD

**Issue by edbartz** [JarodMica/audiobook_maker#63]
I have tried installing this 3 times.  Following each step in the instructions.   Then attempting the test you show.  It never works.  One thing I notice, is it says RVC is not installed.  I downloaded the whl fresh for each install, and followed those steps.  When I test things, the windows tts always works.  When I test tortoise, with use s2s unchecked, I get the following:
C:\Users\xxx\Desktop\TTS\audiobook_maker>call venv\Scripts\activate
[2024-10-22 10:38:19,263] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
RVC not installed, received error: CUDA_HOME does not exist, unable to compile CUDA op(s)
Loading TorToiSe... (AR: None, diffusion: , vocoder: )
Hardware acceleration found: cuda
use_deepspeed api_debug True
C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading tokenizer JSON: C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\tortoise\../tortoise/data/tokenizer.json
Loaded tokenizer
Downloading autoregressive.pth from https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/autoregressive.pth...
100% |########################################################################|
Done.
Loading autoregressive model: C:\Users\xxx\Desktop\TTS\audiobook_maker\models\tortoise\autoregressive.pth
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
Error calling Python override of QThread::run(): Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\controller.py", line 37, in run
    self.function(self.directory_path, self.is_continue, self.report_progress, self.sentence_generated_callback, self.should_stop)
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\model.py", line 260, in generate_audio_for_sentence_threaded
    self.load_selected_tts_engine(tts_engine_name, speaker_id, **speaker_settings)
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\model.py", line 205, in load_selected_tts_engine
    self.tts_engine = tts_engines.load_tts_engine(chosen_tts_engine, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\tts_engines.py", line 80, in load_tts_engine
    raise e
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\tts_engines.py", line 72, in load_tts_engine
    return load_with_tortoise(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\src\tts_engines.py", line 118, in load_with_tortoise
    tts = load_tortoise_engine(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\tortoise_tts_api\inference\load.py", line 38, in load_tts
    tts = TorToise_TTS(
          ^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\tortoise\api.py", line 308, in __init__
    self.load_autoregressive_model(autoregressive_model_path)
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\tortoise\api.py", line 393, in load_autoregressive_model
    self.autoregressive.post_init_gpt2_config(use_deepspeed=self.use_deepspeed, kv_cache=self.use_kv_cache)
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\tortoise\models\autoregressive.py", line 387, in post_init_gpt2_config
    import deepspeed
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\deepspeed\__init__.py", line 25, in <module>
    from . import ops
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\deepspeed\ops\__init__.py", line 15, in <module>
    from ..git_version_info import compatible_ops as __compatible_ops__
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\deepspeed\git_version_info.py", line 29, in <module>
    op_compatible = builder.is_compatible()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\deepspeed\ops\op_builder\fp_quantizer.py", line 35, in is_compatible
    sys_cuda_major, _ = installed_cuda_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\TTS\audiobook_maker\venv\Lib\site-packages\deepspeed\ops\op_builder\builder.py", line 51, in installed_cuda_version
    raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)

**Comment by deffcolony** [comment]
I made a Audiobook-maker launcher which uses miniconda3 to install all requirements 

You can take a look here see if it works for you: https://github.com/JarodMica/audiobook_maker/pull/64

Just make sure to run it from the `audiobook_maker` folder that you already cloned

**Comment by JarodMica** [comment]
Hey @edbartz ,

I believe it comes down to this here: https://developer.nvidia.com/cuda-12-1-0-download-archive

Could you install this and see if it resolves your issue?

I overlooked this stage as I've had it pre installed on my computer for awhile

**Comment by edbartz** [comment]
Interesting.  That fixed it.  Which I don't quite understand, as I had cuda_12.5.0_555.85_windows.exe installed.  Which "appears" to be a newer version,  but thanks. it seems to be working again.   One minor question, using the same tortoise and rvc voice as with the old maker, the rvc result is much deeper voiced.  No clue why, but interesting....  Thanks again.  Keep up the great work!!! I love you stuff.  Now to add in the word replacement stuff I added from the 2.0 maker.

**Comment by JarodMica** [comment]
> Interesting. That fixed it. Which I don't quite understand, as I had cuda_12.5.0_555.85_windows.exe installed. Which "appears" to be a newer version, but thanks. it seems to be working again. Thanks again. Keep up the great work!!! I love you stuff. Now to add in the word replacement stuff I added from the 2.0 maker.

I'm not exactly sure on why RVC require cuda home, but deepspeed I could expect it I guess. I think it's because you need cuda toolkit at 12.1, thought, I thought it should work if you had it at 12.5 as well.

> One minor question, using the same tortoise and rvc voice as with the old maker, the rvc result is much deeper voiced. No clue why, but interesting.... 

There's an unfortunate bug that I think the author of the rvc-python library didn't fix, which was fixed in RVC, but when you use sample rate at 48k, it messes up v1 RVC models. So you can bring that down to 0, I'll have to adjust the default values for it in the config

**Comment by edbartz** [comment]
Jarod, 
   I found the problem with the deep voices.   I looked into how I created the voices, and they were done at 40K, not 48K.  When I adjusted the slider accordingly, it worked fine.  I will either have to recreate the voices, or mod the code for 40k by default.
Thanks again.
Ed (aka physengineer)

**Comment by JarodMica** [comment]
The weird thing is that this is was fixed in the main repo of RVC a long time ago, I guess the author I took the rvc API from used older code possibly... But yes! It works just fine with v2/48k models

**Comment by edbartz** [comment]
I am redoing the voices now, in 48k.  I might as well, since I am using a 3090 now, rather than a 3070ti.   I can't wait for you do the video about setting up tortoise voices (with training).  I tried guessing what I should do with the trained pth file from tortoise, but that failed, so guessing is obviously not my forte, so, I will wait patiently, until you have time.
Ed (aka physengineer)

**Comment by JarodMica** [comment]
Made a patch that changed the way resample SR is chosen 00f4d1cc1c503415d760a58fe9b2f48a776313c9
