### ISSUE TITLE
Is there a download resource for tortoise voices

### ISSUE THREAD

**Issue by Toolfolks** [JarodMica/audiobook_maker#66]
Where and how do I add and use these in audiobook_maker

**Comment by JarodMica** [comment]
No online repo for that unfortunately.

The tortoise repo is here: https://github.com/JarodMica/ai-voice-cloning where you can make your own voices 

Though, it's a bit outdated and needs some love as I believe requirements are causing issues. The packaged version should still work for training tortoise models though

**Comment by craigmediaservices** [comment]
Hi Jarod,

I made a voice model using my voice using your ai-voice-cloning repository. The output sounds good directly.

However the audiobook generator by default seems to "overwrite" output by modifying it with RVC models. Copying the generated pth from the other repository into the voices folder for audiobooks doesn't work (I'm assuming the file is different than expected, or not compatible directly with RVC?).

Is there a way to just disable RVC and directly use output from the ai-voice-cloning in the audiobook generator?

Thank you!

**Comment by JarodMica** [comment]
> Hi Jarod,
> 
> I made a voice model using my voice using your ai-voice-cloning repository. The output sounds good directly.
> 
> However the audiobook generator by default seems to "overwrite" output by modifying it with RVC models. Copying the generated pth from the other repository into the voices folder for audiobooks doesn't work (I'm assuming the file is different than expected, or not compatible directly with RVC?).
> 
> Is there a way to just disable RVC and directly use output from the ai-voice-cloning in the audiobook generator?
> 
> Thank you!
> 
> --
> 
> Nevermind, realised I can just comment out the "rvc" to audio_path line in the Python file. Thank you!

There is a toggleable option for s2s conversion in the audiobook maker, so it shouldn't be too much of an issue.  It makes me think that you may be using an older version of the audiobook maker... but I'm not too sure exactly what you're doing here either.  If you do need clarification, I'm here though :)!
