### ISSUE TITLE
RVC Output is much lower pitched

### ISSUE THREAD

**Issue by Tenidus** [JarodMica/audiobook_maker#71]
I've trained models with your other Tortoise toolbox and also trained RVC models but when I run some tests the output is in a much lower pitch which is odd since the files used for training were all the same.  I wouldn't think the pitch would change upon inference.  Is the default pitch/speed 1 like other RVC tools?  I'm wondering if the default setting is lower by chance.

BTW, this is an incredible tool and I greatly appreciate all of the effort you've put into this and the AI community.

**Comment by Meerfelix** [comment]
I also find the rvc output of lower quality compared to previous versions of the audiobook maker. Is there a possibility to fix this?

**Comment by JarodMica** [comment]
Mentioned here: https://github.com/JarodMica/audiobook_maker/issues/63

Old RVC glitch that seems to have persisted in the library I used the code from.  I'll have to go and patch it but for now, either use 0 for sample rate or you'd have to match the sample rate to the rvc model version you're using (either 40k or 48k)
