### ISSUE TITLE
There's a package incompatibility issue between dlas and f5-tts

### ISSUE THREAD

**Issue by Dragon-Godz** [JarodMica/audiobook_maker#86]
This incompatibility issue causes F5-TTS and Tortoise-TTS to be unable to be installed and used simultaneously. You can only have either or installed, but not both. 

dlas 0.0.1 requires x-transformers==1.0.4
dlas 0.0.1 requires bitsandbytes==0.35.0

However:

f5-tts 0.0.0 requires x-transformers>=1.31.14
f5-tts 0.0.0 requires bitsandbytes>0.37.0

**Comment by JarodMica** [comment]
This is ok, no hindrance to the functionality of the project
