### ISSUE TITLE
Styletts2 reference file issues.

### ISSUE THREAD

**Issue by edbartz** [JarodMica/audiobook_maker#89]
In addition to the nltk problem mentioned separately,  I see one other issue with styletts.  Given multiple voice files,  say voice A, and B, and C.   If you select voice C,  it lists Voice Reference File: C.wav.  But then errors with:
FileNotFoundError: [Errno 2] No such file or directory: './voices/styletts\\C\\A.wav'

This error occurs regardless of which voice I choice, other than A.

Ed

**Comment by JarodMica** [comment]
This is fixed here, please test it out to see if you run into anymore issues: https://github.com/JarodMica/audiobook_maker/commit/616fd26e4d692a79c735f5209bb5b68ca127020a

**Comment by edbartz** [comment]
Yes, this is also fixed
Thanks
Ed
